name: pc
channels:
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgomp=15.1.0=h767d61c_5
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libuuid=2.41.1=he9a06e4_0
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.2=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.11.0=he550d4f_1_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - pip:
      - addict==2.4.0
      - asttokens==3.0.0
      - attrs==25.3.0
      - blinker==1.9.0
      - catkin-pkg==1.1.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - dash==3.2.0
      - decorator==5.2.1
      - docutils==0.22
      - em==0.4.0
      - empy==3.3.4
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - fire==0.7.1
      - flask==3.1.2
      - fonttools==4.59.2
      - fsspec==2025.9.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - ipython==9.5.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - laspy==2.6.1
      - lazrs==0.7.0
      - markupsafe==3.0.2
      - matplotlib==3.10.6
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - narwhals==2.4.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - numpy==2.3.3
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.6.77
      - open3d==0.19.0
      - packaging==25.0
      - pandas==2.3.2
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.4.0
      - plotly==6.3.0
      - prompt-toolkit==3.0.52
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.5
      - retrying==1.4.2
      - rpds-py==0.27.1
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - torch==2.9.0+cu126
      - torchvision==0.24.0+cu126
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.5.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - zipp==3.23.0
prefix: /home/ak1ra/miniconda3/envs/pc
